CREATE DATABASE PLANT_DESEASE;
USE PLANT_DESEASE;
CREATE TABLE DESEASE_INFO(
	id INT AUTO_INCREMENT PRIMARY KEY,
    IMAGES VARCHAR(255),
    INFO VARCHAR(255)
);

DROP TABLE DESEASE_INFO;
SELECT * FROM DESEASE_INFO